site_name: An Implementation of Docs as Code
theme:
  name: material
  favicon: images/typewriter.png 
  logo: images/typewriter.png
  palette:
    primary: white
    accent: white
nav:
  - Home: index.md
  - Step 1 Create the Static Site: step1.md
  - Step 2 Create a GitHub Repository: step2.md
  - Step 3 Add the Vale YAML Extension files: step3.md
  - Step 4 Create the continuous integration workflow: step4.md
  - Step 5 Create the continuous deployment workflow: step5.md